config/routes.rb
Rails.application.routes.draw do
  
  root to: "homes#top"
  devise_for :users
  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy ] do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image
  
  validates :title,presence:true
  validates :body,presence:true, length: { maximum: 200  }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end 
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment,presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: { case_sensitive: false }, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    @user = current_user
    user_path(@user.id)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def user_info_new_book
    @user = current_user
    @book = Book.new
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :current_user, only: [:destroy]

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    if comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    BookComment.find_by(id: params[:id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :user_info_new_book, only: [:index, :show]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    user_info_new_book
    @books = Book.all
  end

  def show
    user_info_new_book
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    is_matching_login_user
    @book = Book.find(params[:id])
  end

  def update
    is_matching_login_user
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    @book = Book.find(params[:id])
    user_id = @book.user.id
    login_user_id = current_user.id
    if (user_id != login_user_id )
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
    redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :user_info_new_book, only: [:index, :show]

  def edit
    is_matching_login_user
    @user = User.find(params[:id])
  end

  def index
    user_info_new_book
    @users = User.all
    @book = Book.new
  end

  def show
    user_info_new_book
    @user = User.find(params[:id])
    @books = @user.books.all
  end

  def update
    is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image , :introduction)
  end

  def is_matching_login_user
    user_id = params[:id].to_i
    login_user_id = current_user.id
    if (user_id != login_user_id )
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      
    <h2>Editing Book</h2>
    
    <%= form_with model: @book do |f| %>
    <div class="form-group">
     <label for="book_title">Title</label>
      <%= f.text_field :title,class:"form-control book_title" %>
    </div>
    
    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body,class:"form-control book_body" %>
    </div>
    
    <div class="form-group">
      <%= f.submit 'Update Book',class:"btn btn-success" %>
    </div>
    <% end %>
    
     <%= link_to book_path,class:"book_52734" do %>Show<% end %>
      |
     <%= link_to books_path,class:"back" do %>Back<% end %>
    </form>
  
 </div>
</div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">

  <div id="error_explanation">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-3">

  <!--Useinfo部分-->
      <h2>User info</h2>
      <table class ="table">
        <tbody>
          <tr></tr>

         <!--画像-->
          <% if @user.profile_image.attached? %>
           <%= image_tag @user.profile_image, size: "100x100" %>
          <% else %>
           <%= image_tag 'default-image', size: "100x100" %>
          <% end %>

         <h5>name</h5>
          <%= @user.name %>
         <h5>introduction</h5>
          <%= @user.introduction %>
        </tbody>
      </table>

    <!--ボタン-->
      <div class ="row">
        <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

      <h2>New book</h2>
      <!-- form_with部分 -->
       <%= form_with model: @book do |f| %>
       <div class="form-group">
        <h4>Title</h4>
         <%= f.text_field :title, class:"form-control book_title" %>
       </div>

       <div class="form-group">
        <h4>Opinion</h4>
        <%= f.text_field :body, class:"form-control book_body" %>
       </div>

       <div class="form-group">
        <%= f.submit 'Create Book', class:"btn btn-success" %>
       </div>
      <% end %>

    </div>


    <div class="col-md-8 offset-md-1">

      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <!--<th colspan="3"></th>-->
        </thead>

        <tbody>
        <% @books.each do |books|%>
            <tr>
              <td>
                <%= link_to user_path(books.user.id) do %>
                  <%= image_tag books.user.get_profile_image(80, 80) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(books.id) do %>
                  <%= books.title %>
                <% end %>
              </td>
              <td>
                <%= books.body %>
              </td>
              
              <td>
           <% if books.favorited_by?(current_user) %>

            <%= link_to book_favorites_path(books), class: "fas fa-heart red", method: :delete do %>
            <%= books.favorites.count %>
            <% end %>

           <% else %>

            <%= link_to book_favorites_path(books), class: "fas fa-heart", method: :post do %>
              <%= books.favorites.count %>
            <% end %>

            <% end %>
          </td>
          
            <th>
            <%= "#{books.book_comments.count} コメント" %>
          </th>
            </tr>
          </tbody>

        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">

  <div id="error_explanation">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-3">

      <h2>User info</h2>
      <%= image_tag current_user.get_profile_image(100,100) %>
      <table class="table">
       <tbody>
        <tr></tr>
        <tr>
         <th>name</th>
          <th><%= @user.name %></th>
        </tr>

        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
       </tbody>
      </table>

   <div class="row">
    <%= link_to edit_user_path(@user),class:"btn btn-outline-secondary btn-block edit_user_path" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
   </div>

    <h2 class="mt-3">New book</h2>
    <%= form_with model: Book.new do |f| %>

      <div class="form-group">
       <label for="book_title">Title</label>
       <%= f.text_field :title,class:"form-control book_title" %>
      </div>

      <div class="form-group">
       <label for="book_opinion">Opinion</label>
       <%= f.text_area :body,class:"form-control book_body" %>
      </div>

      <div class="form-group">
       <%= f.submit 'Create Book',class:"btn btn-success" %>
     </div>
    </div>
    <% end %>

    <div class="col-md-8 offset-md-1">

      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user.id) do %>
                  <%= image_tag @book.user.get_profile_image(80, 80) %><br>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book.id) do %>
                  <%= @book.title %>
                <% end %>
              </td>
              <td>
                <%= @book.body %>
              </td>

              <td>
               <% if @book.favorited_by?(current_user) %>

                <%= link_to book_favorites_path(@book), class: "fas fa-heart red", method: :delete do %>
                  <%= @book.favorites.count %>
                <% end %>

               <% else %>

                <%= link_to book_favorites_path(@book), class: "fas fa-heart", method: :post do %>
                  <%= @book.favorites.count %>
                <% end %>

               <% end %>
              </td>

               <td>
                  コメント数:<%= @book.book_comments.count %>
               </td>

              <tbody>
              <% @book.book_comments.each do |book_comment| %>
                <tr>
                <td>
                  <%= image_tag book_comment.user.get_profile_image(100,100) %>
                  <%= link_to book_comment.user.name , user_path(@book.user.id)  %>
                  <%= book_comment.comment %>
                  <% if book_comment.user == current_user %>
                  <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
                  <% end %>
                </td>
                <% end %>

                <td>
                <%= form_with model: [@book, @book_comment] do |f| %>
                  <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" , :size => "50x6" %>
                 <P><%= f.submit "送信する" %></P>
                <% end %>
                </td>
              </tr>
              </tbody>


              <% if @book.user.id == current_user.id %>
                <td>
                  <%= link_to 'Edit', edit_book_path(@book.id), class: 'btn btn-sm btn-success' %>
                </td>
                <td>
                  <%= link_to 'Destroy', book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class: 'btn btn-sm btn-danger' %>
                </td>
              <% end %>
            </tr>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/7d4686f8ad.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
   <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class: 'navbar-brand' do %>
            <span>Bookers</span>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                    <i class="fas fa-home"></i>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-users"></i>
                    Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-book-open"></i>
                    Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt"></i>
                    logout
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-home"></i>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-link"></i>
                    About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-user-plus"></i>
                   sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-in-alt"></i>
                    login
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main>
    <p id="notice"><%= flash[:notice] %></p>
    <%= yield %>
    </main>
    
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>

</html>

app/views/users/_list.html.erb
<h2>User info</h1>
<div>
  <%= image_tag user.get_profile_image(100, 100) %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to edit_user_path(user.id), class:'btn btn-outline-secondary btn-block' do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
</div>

<h2 class="mt-3">New book</h2>
<%= form_with model: book do |f|%>
  <div class="form-group">
    <div class="field_with_errors">
      <label for="book_title">Title</label>
    </div>
    <div class="field_with_errors">
      <%= f.text_field :title, class:"form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="field_with_errors">
      <label for="book_opinion">Opinion</label>
    </div>
    <div class="field_with_errors">
      <%= f.text_area :body, class:"form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>

<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <!-- エラーメッセージ -->
      <div id="error_explanation">
        <% if @user.errors.any? %>
          <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <!-- ユーザー情報入力フォーム -->
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <div class="field_with_errors">
            <label for="user_name">Name</label>
          </div>
          <div class="field_with_errors">
            <%= f.text_field :name, autofocus: true, class: "form-control name", id:"user_name" %>
          </div>
        </div>
        <div class="form-group">
          <div class="field_with_errors">
            <label for="user_image">Image</label>
          </div>
          <div class="field_with_errors">
            <%= f.file_field :profile_image, placeholder: "ファイルを選択", accept: "image/*", class: "form-container-file user_image", id: "user_profile_image" %>
          </div>
        </div>
        <div class="form-group">
          <div class="field_with_errors">
            <label for="user_introduction">Introduction</label>
          </div>
          <div class="field_with_errors">
            <%= f.text_area :introduction, autofocus: true, class: "form-control introduction", id: "user_introduction" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">

  <div id="error_explanation">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="row">

    <div class="col-md-3">
      <%= render 'list', user: @user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </thead>
        <% @users.each do |users|%>
          <tbody>
            <tr>
              <td>
                <%= image_tag users.get_profile_image(80, 80) %>
              </td>
              <td>
                <%= users.name %>
              </td>
              <td>
                <%= link_to "Show", user_path(users.id) %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">

  <div id="error_explanation">
   <%= flash[:notice] %>
  </div>
  <p id="notice"></p>

  <div class="row">
    <div class="col-md-3">

      <%= render 'list', user: @user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">

      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </thead>
        <% @books.each do |books|%>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(books.user.id) do %>
                  <%= image_tag books.user.get_profile_image(80, 80) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(books.id) do %>
                  <%= books.title %>
                <% end %>
              </td>
              <td>
                <%= books.body %>
              </td>

              <td>
               <% if books.favorited_by?(current_user) %>

                <%= link_to book_favorites_path(books), class: "fas fa-heart red", method: :delete do %>
                  <%= books.favorites.count %>
              <% end %>

               <% else %>

                <%= link_to book_favorites_path(books), class: "fas fa-heart", method: :post do %>
                 <%= books.favorites.count %>
                <% end %>

               <% end %>
              </td>

               <td>
                  コメント数:<%= @book.book_comments.count %>
               </td>


            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>